name: Cypress Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    strategy:
      matrix:
        browsers: [chrome]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install and Build
        run: |
          npm i
          npm run build
          npm install -g serve
          
      - name: Create env
        run: |
          touch .env
          echo REACT_APP_GOOGLE_CLIENT_ID=${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }} >> .env
          echo REACT_APP_FIREBASE_API_KEY=${{ secrets.REACT_APP_FIREBASE_API_KEY }} >> .env
          echo REACT_APP_GRAPHQL_ENDPOINT=${{ secrets.REACT_APP_GRAPHQL_ENDPOINT }} >> .env
          cat .env
          
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: serve -s build
          wait-on: http://localhost:3000
          wait-on-timeout: 1200
          config: baseUrl=http://localhost:3000
          browser: ${{ matrix.browsers }}
          headless: true
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
